AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple Hello World Serverless project
Resources:
  myapp:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: myapp
      CodeUri: .
      Timeout: 5
      Environment:
        Variables:
          SECRET: "d68a6170-98da-4c83-bcd6-1155b6908399" # Replace this with your token
